version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: bundle exec rails server --binding 0.0.0.0
    volumes:
      - ".:/app"
      - bundle:/bundle
      - "../sidekiq-staged_push:/sidekiq-staged_push"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: bundle exec sidekiq
    volumes:
      - ".:/app"
      - bundle:/bundle
      - "../sidekiq-staged_push:/sidekiq-staged_push"
    depends_on:
      - db
      - redis
  db:
    image: "healthcheck/postgres:alpine"
    environment:
      POSTGRES_PASSWORD: db_password
  redis:
    image: "redis:6-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
volumes:
  bundle:
  redis:
