name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/adamniedzielski/sidekiq-staged_push-demo:${{ github.sha }}
          target: ci
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/adamniedzielski/sidekiq-staged_push-demo:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: /app

    steps:
      - name: Run Rubocop
        run: |
          bundle exec rubocop
